package term_sys_ansi

import "core:terminal/ansi"

// https://en.wikipedia.org/wiki/ANSI_escape_code
// https://invisible-island.net/xterm/ctlseqs/ctlseqs.html

CSI_ENDING_BEGIN_STATE :: "h"
CSI_ENDING_END_STATE :: "l"

CSI_STYLE_RESET :: ansi.CSI + ansi.RESET + ansi.SGR
CSI_CLEAR_SCREEN :: ansi.CSI + "2J"
CSI_ERASE_BELOW :: ansi.CSI + "0J"
CSI_ERASE_LINE_RIGHT :: ansi.CSI + "0K"
CSI_CURSOR_MOVE_HOME :: ansi.CSI + "H"

// X10 compatibility mode: report button press only.
MOUSE_TRACKING :: "?1000"
CSI_MOUSE_TRACKING_UP :: ansi.CSI + MOUSE_TRACKING + CSI_ENDING_BEGIN_STATE
CSI_MOUSE_TRACKING_DOWN :: ansi.CSI + MOUSE_TRACKING + CSI_ENDING_END_STATE

// Report motion while a button is held.
MOUSE_DRAGING :: "?1002"
CSI_MOUSE_DRAGING_UP :: ansi.CSI + MOUSE_DRAGING + CSI_ENDING_BEGIN_STATE
CSI_MOUSE_DRAGING_DOWN :: ansi.CSI + MOUSE_DRAGING + CSI_ENDING_END_STATE

// Report all motion.
MOUSE_ALL_MOTION_TRACKING :: "?1003"
CSI_MOUSE_ALL_MOTION_TRACKING_UP :: ansi.CSI + MOUSE_ALL_MOTION_TRACKING + CSI_ENDING_BEGIN_STATE
CSI_MOUSE_ALL_MOTION_TRACKING_DOWN :: ansi.CSI + MOUSE_ALL_MOTION_TRACKING + CSI_ENDING_END_STATE

// SGR (1006) mouse reporting: `CSI < Cb ; Cx ; Cy M|m`, unlimited coordinates.
MOUSE_EXTENDING_TRACKING :: "?1006"
CSI_MOUSE_EXTENDING_TRACKING_UP :: ansi.CSI + MOUSE_EXTENDING_TRACKING + CSI_ENDING_BEGIN_STATE
CSI_MOUSE_EXTENDING_TRACKING_DOWN :: ansi.CSI + MOUSE_EXTENDING_TRACKING + CSI_ENDING_END_STATE

// URxvt extended mouse mode (fallback for terminals without 1006).
MOUSE_EXTENDING_MODE :: "?1015"
CSI_MOUSE_EXTENDING_MODE_UP :: ansi.CSI + MOUSE_EXTENDING_MODE + CSI_ENDING_BEGIN_STATE
CSI_MOUSE_EXTENDING_MODE_DOWN :: ansi.CSI + MOUSE_EXTENDING_MODE + CSI_ENDING_END_STATE

ALTERNATE_MODE :: "?1049"
CSI_ALTERNATE_MODE_UP :: ansi.CSI + ALTERNATE_MODE + CSI_ENDING_BEGIN_STATE
CSI_ALTERNATE_MODE_DOWN :: ansi.CSI + ALTERNATE_MODE + CSI_ENDING_END_STATE

CSI_SHOW_CURSOR :: ansi.CSI + ansi.DECTCEM_SHOW
CSI_HIDE_CURSOR :: ansi.CSI + ansi.DECTCEM_HIDE

// Wraps a frame so the terminal presents it atomically (no tearing).
SYNC_UPDATE :: "?2026"
CSI_SYNC_UPDATE_UP :: ansi.CSI + SYNC_UPDATE + CSI_ENDING_BEGIN_STATE
CSI_SYNC_UPDATE_DOWN :: ansi.CSI + SYNC_UPDATE + CSI_ENDING_END_STATE

// Pasted text arrives wrapped in `CSI 200 ~` ... `CSI 201 ~`.
BRACKETED_PASTE :: "?2004"
CSI_BRACKETED_PASTE_UP :: ansi.CSI + BRACKETED_PASTE + CSI_ENDING_BEGIN_STATE
CSI_BRACKETED_PASTE_DOWN :: ansi.CSI + BRACKETED_PASTE + CSI_ENDING_END_STATE

// Terminal reports `CSI I` on focus gained and `CSI O` on focus lost.
FOCUS_EVENTS :: "?1004"
CSI_FOCUS_EVENTS_UP :: ansi.CSI + FOCUS_EVENTS + CSI_ENDING_BEGIN_STATE
CSI_FOCUS_EVENTS_DOWN :: ansi.CSI + FOCUS_EVENTS + CSI_ENDING_END_STATE
